/*
    <시퀀스 >
    
    정수값을 자동으로 순차적으로 생성해줌
    


    
*/

/*
    1. 시퀀스객체 생성 구문
    
    [표현법]
    CREATE SEQUENCE 시퀀스명;
    
    
    
*/

--테이블명 : TB_
--뷰명 : VW_
--시퀀스명 : SEQ_
--트리거명 : TRG_


CREATE SEQUENCE SEQ_EMPNO

MAXVALUE 310
NOCYCLE
NOCACHE;


SELECT SEQ_EMPNO.CURRVAL FROM DUAL;

SELECT SEQ_EMPNO.NEXTVAL FROM DUAL;

SELECT SEQ_EMPNO.CURRVAL FROM DUAL;


ALTER SEQUENCE SEQ_EMPNO
INCREMENT BY 10
MAXVALUE 400;

SELECT * FROM USER_SEQUENCES;

SELECT SEQ_EMPNO.NEXTVAL FROM DUAL;

------------------------------------------------------

--매번 새로운 사번이 발생되게끔 시퀀스 생성

CREATE SEQUENCE SEQ_EID
START WITH 300;

SELECT * FROM USER_SEQUENCES;

INSERT INTO EMPLOYEE(EMP_ID, EMP_NAME ,EMP_NO, JOB_CODE, HIRE_DATE)
VALUES (SEQ_EID.NEXTVAL, '홍길동', '111111-111111', 'J1', SYSDATE);

INSERT INTO EMPLOYEE(EMP_ID, EMP_NAME ,EMP_NO, JOB_CODE, HIRE_DATE)
VALUES (SEQ_EID.NEXTVAL, '홍길녀', '2222222-111111', 'J2', SYSDATE);

INSERT INTO EMPLOYEE(EMP_ID, EMP_NAME ,EMP_NO, JOB_CODE, HIRE_DATE)
VALUES (SEQ_EID.NEXTVAL, '김말똥', '2222-1111', 'J4', SYSDATE);






